"""
This module contains label information for Output and MSMask or FreeSurferColorLUT.txt

Output labels:
    1  ==  Periventricular
    2  ==  Juxtacortical
    3  ==  Subcortical
    4  ==  Infratentorial

MSMask labels:
    0  ==  Background
    1  ==  CSF
    2  ==  GM
    3  ==  WM
    4  ==  Ventricles
    5  ==  Infratentorial





"""
import shlex
import subprocess
import os
from pathlib import Path

import nibabel as nib
import numpy as np
from scipy.ndimage import label as label_scipy
from skimage.measure import label 
from skimage.morphology import binary_dilation
from scipy.ndimage import generate_binary_structure
import ants

"""
np.unique output from aparc.DKTatlas+aseg.deep.mgz
array([   0,    2,    4,    5,    7,    8,   10,   11,   12,   13,   14,
         15,   16,   17,   18,   24,   26,   28,   31,   41,   43,   44,
         46,   47,   49,   50,   51,   52,   53,   54,   58,   60,   63,
         77, 1002, 1003, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012,
       1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023,
       1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1034, 1035, 2002,
       2003, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025,
       2026, 2027, 2028, 2029, 2030, 2031, 2034, 2035])
"""

def remove_small_objects(data, dim_lst, unit='mm3', thr=0):
    """Removes all unconnected objects smaller than the minimum specified size.

    Adapted from:
    https://github.com/ivadomed/ivadomed/blob/master/ivadomed/postprocessing.py#L327
    and
    https://github.com/ivadomed/ivadomed/blob/master/ivadomed/postprocessing.py#L224

    Args:
        data (ndarray): Input data.
        dim_lst (list): Dimensions of a voxel in mm.
        unit (str): Indicates the units of the objects: "mm3" or "vox"
        thr (float): Minimal object size to keep in input data.

    Returns:
        ndarray: Array with small objects.
    """
    print(f"Thresholding lesions at [mm3]:{np.prod(dim_lst)}")

    px, py, pz = dim_lst

    # structuring element that defines feature connections
    bin_structure = generate_binary_structure(3, 2)

    data_label, n = label_scipy(data, structure=bin_structure)

    if unit == 'mm3':
        size_min = np.round(thr / (px * py * pz))
    else:
        print('Please choose a different unit for removeSmall. Choices: vox or mm3')
        exit()

    for idx in range(1, n + 1):
        data_idx = (data_label == idx).astype(int)
        n_nonzero = np.count_nonzero(data_idx)

        if n_nonzero < size_min:
            data[data_label == idx] = 0

    return data

def annotate_lesions_fsseg(lst_seg, fs_seg , out_annotated_native):
    """
    Annotate lesions in a given image using an atlas.
    Modified function form original LST-AI function (see above).
    Key difference: instead of a template this function uses the segmentation file generated by the "fastsurfer" freesurfer-implementation.
    Tissue-segmentation already exists in native space, no registration is required therefore.

    Parameters:
    -----------
    atlas_t1: str
        Path to the atlas T1-weighted image (in MNI space).
    atlas_mask: str
        Path to the atlas mask image.
    t1w_native: str
        Path to the T1-weighted image in native space.
    lst_seg: str
        Path to the segmentation image in native space.
    out_atlas_warp: str
        Path where the warp from the atlas to the patient T1 should be saved.
    fs_seg: str
        Path where the freesurfer output was saved.
    out_annotated_native: str
        Path where the annotated lesion segmentation in native space should be saved.

    Description:
    ------------
    The function performs several tasks:
    1. Registers the atlas to the patient's T1 image using a two-step greedy algorithm.
    2. Warps the atlas mask to the patient's space.
    3. Annotates lesions based on the overlap with the atlas mask.
    4. Saves the annotated segmentation in native space.

    Returns:
    --------
    None

    """

    #######
    # modify here
        # get freesurfer segmentation label dictionary!>
    #######
    freesurfer_to_msmask = {
        # Background:
        0:0,

        # CSF
        24: 1,

        # Cortex (2)
        **{i: 2 for i in range(1000, 1036)},     # Left hemisphere cortex (ctx-lh-*)
        **{i: 2 for i in range(2000, 2036)},     # Right hemisphere cortex (ctx-rh-*)

        # Supratentorial white matter (3)
        2: 3,    # Left-Cerebral-White-Matter
        41: 3,   # Right-Cerebral-White-Matter
        # Deep GM, counted as WM for this analysis
        10: 3,   # Left-Thalamus
        11: 3,   # Left-Caudate
        12: 3, 
        13: 3,
        26: 3,
        28:3,    # Left-VentralDC
        49: 3,   # Right-Thalamus
        50: 3,   # Rigtht-Caudate
        51:3 ,
        52:3,
        53:3,
        54:3,
        58:3,
        60:3,    # Right-VentralDC   
        # HC
        17:3,
        # Amygdala
        18: 3,
        77:0,     # WM-hypointensities 
        # Corpus Callosum
        250:3, # Fornix
        251:3, # CC_Posterior                            0   0   64  0
        252:3, # CC_Mid_Posterior                        0   0   112 0
        253:3, # CC_Central                              0   0   160 0
        254:3, # CC_Mid_Anterior                         0   0   208 0
        255:3, # CC_Anterior                             0   0   255 0
        # Lateral and 3rd ventricles (4)
        4: 4,    # Left-Lateral-Ventricle
        5: 4,    # Left-Inf-Lat-Vent
        31: 4,
        63: 4,   # Right-choroid-plexus
        43: 4,   # Right-Lateral-Ventricle
        44: 4,   # Right-Inf-Lat-Vent
        14: 4,   # 3rd Ventricle

        # Infratentorial structures (5)
        16: 5,   # Brain-Stem
        27: 5,
        15: 5,   # 4th ventricle
        7: 5,    # Left-Cerebellum-White-Matter
        8: 5,    # Left-Cerebellum-Cortex
        46: 5,   # Right-Cerebellum-White-Matter
        47: 5,   # Right-Cerebellum-Cortex

    }
    

    # Load segmentation and msmask and location-label lesions
    lst_seg_nib = nib.load(lst_seg)
    lst_seg = lst_seg_nib.get_fdata()
    lst_seg[lst_seg > 0] = 1  # Make sure seg is binary
    lst_seg = lst_seg.astype(np.uint8)
    
    fs_seg = nib.load(fs_seg).get_fdata()
    fu = np.vectorize(lambda x: freesurfer_to_msmask.get(x, 0))
    fs_seg_mapped = fu(fs_seg)

    lst_seg_label = label(lst_seg, connectivity=3)
    for lesion_ctr in range(1, lst_seg.max() + 1):
        # We create a temporary binary mask
        # for each lesion & dilate it by 1
        # (to "catch" adjacent structures)
        temp_mask = np.zeros(lst_seg.shape)
        temp_mask[lst_seg_label == lesion_ctr] = 1
        temp_mask_dil = binary_dilation(
            temp_mask, footprint=np.ones((3, 3, 3))).astype(np.uint8)

        if 4 in fs_seg_mapped[temp_mask_dil == 1]:
            lst_seg[temp_mask == 1] = 1  # PV

        elif 2 in fs_seg_mapped[temp_mask_dil == 1]:
            lst_seg[temp_mask == 1] = 2  # JC

        elif 5 in fs_seg_mapped[temp_mask_dil == 1]:
            lst_seg[temp_mask == 1] = 4  # IT

        else:
            lst_seg[temp_mask == 1] = 3  # SC

    # Saving & warping back to T1w space ### requires testing: lst-segmentation and fs-segmentation in the same reference space?
    nib.save(nib.Nifti1Image(lst_seg.astype(np.uint8),
                             lst_seg_nib.affine, lst_seg_nib.header),
                             out_annotated_native)
    


def annotate_lesions_fsseg_variablethresh(probmap, fs_seg , out_annotated_native , thresh_jc = 0.350 , thresh_other = 0.500 , lesion_thresh = 0):
    """
    Annotate lesions in a given image using an atlas.
    Modified function form original LST-AI function.
    Additionally, allows the user to specify several probability thresholds for different lesion types.

    Parameters:
    -----------
    probmap: lesion probability map output from LST-AI main processing script
    fs_seg:  aparc.DKTatlas+aseg.deep.mgz output from freesurfer : tissue type segmentation
    out_annotated_native: output filename in t1 native space ::: modify here  -  provide registration functionality?
    thresh_jc: heuristic threshold for detection of juxtacortical lesions
    thresh_other: heuristic thresold for detection of all other lesion types

    Description:
    ------------
    provide description

    Returns:
    --------
    None

    """

    #######
    # get freesurfer segmentation label dictionary!>
    #######
    freesurfer_to_msmask = {
        # Background:
        0:0,

        # CSF
        24: 1,

        # Cortex (2)
        **{i: 2 for i in range(1000, 1036)},     # Left hemisphere cortex (ctx-lh-*)
        **{i: 2 for i in range(2000, 2036)},     # Right hemisphere cortex (ctx-rh-*)

        # Supratentorial white matter (3)
        2: 3,    # Left-Cerebral-White-Matter
        41: 3,   # Right-Cerebral-White-Matter
        # Deep GM, counted as WM for this analysis
        10: 3,   # Left-Thalamus
        11: 3,   # Left-Caudate
        12: 3, 
        13: 3,
        26: 3,
        28:3,    # Left-VentralDC
        49: 3,   # Right-Thalamus
        50: 3,   # Rigtht-Caudate
        51:3 ,
        52:3,
        53:3,
        54:3,
        58:3,
        60:3,    # Right-VentralDC   
        # HC
        17:3,
        # Amygdala
        18: 3,
        77:0,     # WM-hypointensities 
        # Corpus Callosum
        250:3, # Fornix
        251:3, # CC_Posterior                            0   0   64  0
        252:3, # CC_Mid_Posterior                        0   0   112 0
        253:3, # CC_Central                              0   0   160 0
        254:3, # CC_Mid_Anterior                         0   0   208 0
        255:3, # CC_Anterior                             0   0   255 0
        # Lateral and 3rd ventricles (4)
        4: 4,    # Left-Lateral-Ventricle
        5: 4,    # Left-Inf-Lat-Vent
        31: 4,
        63: 4,   # Right-choroid-plexus
        43: 4,   # Right-Lateral-Ventricle
        44: 4,   # Right-Inf-Lat-Vent
        14: 4,   # 3rd Ventricle

        # Infratentorial structures (5)
        16: 5,   # Brain-Stem
        27: 5,
        15: 5,   # 4th ventricle
        7: 5,    # Left-Cerebellum-White-Matter
        8: 5,    # Left-Cerebellum-Cortex
        46: 5,   # Right-Cerebellum-White-Matter
        47: 5,   # Right-Cerebellum-Cortex

    }
    # resample the fs segmentation to the t1 native space:
    fs_seg_ants = ants.image_read(fs_seg)
    probmap_ants = ants.image_read(probmap)
    fs_seg_ants = fs_seg_ants.resample_image_to_target(probmap_ants , interp_type = 'nearestNeighbor')
    ants.image_write(fs_seg_ants , fs_seg.split('.')[0] + '_reshaped.nii.gz')
    # Load probmap and fs seg
    probmap_nib = nib.load(probmap)
    probmap = probmap_nib.get_fdata()
    

    
    fs_seg = nib.load(fs_seg.split('.')[0] + '_reshaped.nii.gz').get_fdata()
    fu = np.vectorize(lambda x: freesurfer_to_msmask.get(x, 0))
    fs_seg_mapped = fu(fs_seg)

    # generate empty array to collect lesions:
    seg_out = np.zeros(shape = probmap.shape)

    # binarise probmap according to jc thresh:
    seg_jc = np.zeros(probmap.shape)
    seg_jc[probmap > thresh_jc] = 1
    seg_jc = remove_small_objects(seg_jc, probmap_nib.header.get_zooms(), unit="mm3", thr=int(lesion_thresh))

    jc_seg_label = label(seg_jc, connectivity=3)
    print(f'number of lesions with threshold {thresh_jc}: {jc_seg_label.max()}')
    
    for lesion_ctr in range(1, jc_seg_label.max() + 1):
        # We create a temporary binary mask
        # for each lesion & dilate it by 1
        # (to "catch" adjacent structures)
        temp_mask = np.zeros(seg_jc.shape)
        temp_mask[jc_seg_label == lesion_ctr] = 1
        temp_mask_dil = binary_dilation(
            temp_mask, footprint=np.ones((3, 3, 3))).astype(np.uint8)
        
        if 4 in fs_seg_mapped[temp_mask_dil == 1]:
            # lesion not counted as juxtacortical, more likely periventricular (see next step)
            continue

        elif 2 in fs_seg_mapped[temp_mask_dil == 1]:
            # don't count JC twice
            seg_out[temp_mask == 1] = 2  # JC
            
        elif 5 in fs_seg_mapped[temp_mask_dil == 1]:
            continue
    
        else:
            continue

        # elif 2 in fs_seg_mapped[temp_mask_dil == 1]:
    

    # other lesion types:
    seg_other = np.zeros(probmap.shape)
    seg_other[probmap > thresh_other] = 1
    seg_other = remove_small_objects(seg_other, probmap_nib.header.get_zooms(), unit="mm3", thr=int(lesion_thresh))
    
    other_seg_label = label(seg_other, connectivity=3)
    print(f'number of lesions  with threshold {thresh_other}: {other_seg_label.max()}')
    for lesion_ctr in range(1, other_seg_label.max() + 1):
        # We create a temporary binary mask
        # for each lesion & dilate it by 1
        # (to "catch" adjacent structures)
        temp_mask = np.zeros(seg_other.shape)
        temp_mask[other_seg_label == lesion_ctr] = 1
        temp_mask_dil = binary_dilation(
            temp_mask, footprint=np.ones((3, 3, 3))).astype(np.uint8)

        if 2 in seg_out[temp_mask_dil == 1]:
            # avoid overwriting lesions.
            continue
        else:
            if 4 in fs_seg_mapped[temp_mask_dil == 1]:
                seg_out[temp_mask == 1] = 1  # PV

            # elif 2 in fs_seg_mapped[temp_mask_dil == 1]:
            #     # don't count JC twice
            #     continue

            elif 5 in fs_seg_mapped[temp_mask_dil == 1]:
                seg_out[temp_mask == 1] = 4  # IT

            else:
                seg_out[temp_mask == 1] = 3  # SC

    # Saving & warping back to T1w space ### requires testing: lst-segmentation and fs-segmentation in the same reference space?
    # Saving & warping back to T1w space
    print(f'saving new annotation ... {Path(out_annotated_native).name}')
    # nib.save(nib.Nifti1Image(fs_seg_mapped.astype(np.uint8),
    #                          probmap_nib.affine, probmap_nib.header),
    #                          out_annotated_native )
    nib.save(nib.Nifti1Image(seg_out.astype(np.uint8),
                             probmap_nib.affine, probmap_nib.header),
                             out_annotated_native)
if __name__ == "__main__":

    # Only for testing purposes
    data_dir = '/mnt/d/TWIN_MRI/'
    bids_dir = data_dir + 'BIDS_directories/'
    bids_dir_prisma = bids_dir + 'TEST/'
    subject = '73' 
    session = '07102019'
    lst_dir = bids_dir_prisma + f'derivatives/lst-ai-v1.2.0_docker/' + f'sub-{subject}/ses-{session}/temp/'

    # annotate lesion test data
    probmap = os.path.join(lst_dir, f"sub-{subject}_ses-{session}_space-FLAIR_seg-lst_prob.nii.gz")
    fs_seg  = bids_dir_prisma + f'derivatives/fastsurfer_v2.4.2_docker/' + f'sub-{subject}/ses-{session}/sub-{subject}_ses-{session}/mri/aparc.DKTatlas+aseg.mapped.mgz'
    
    out_annotated_native = os.path.join(lst_dir, f"sub-{subject}_ses-{session}_annotated_segmentation.nii.gz")

    annotate_lesions_fsseg_variablethresh(probmap, fs_seg , out_annotated_native)

    # check and remove testing results
    # gt = os.path.join(lst_dir, "testing", "annotation",
    #                   "sub-msseg-test-center01-02_ses-01_space-mni_annotated_seg.nii.gz")
    # array_gt = nib.load(gt).get_fdata()
    # array_pred = nib.load(annotated_seg_path).get_fdata()
    # os.remove(out_atlas_mask_warped_path)
    # os.remove(out_atlas_warp_path)
    # os.remove(annotated_seg_path)
    # np.testing.assert_array_equal(array_gt, array_pred)
